# Generated by Django 2.1 on 2018-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180826_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='main_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
