# Generated by Django 2.1 on 2018-08-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20180826_1703'),
        ('post', '0005_post_user'),
    ]

    operations = [
    ]
