# Generated by Django 2.1 on 2018-09-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('is_shown', models.BooleanField(default=False)),
                ('you', models.BooleanField(default=False)),
                ('data', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
