# Generated by Django 2.1 on 2018-09-11 12:45

import core.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequests',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hashed_token', models.BinaryField(max_length=32)),
                ('req_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_username', models.CharField(max_length=200)),
                ('fullname', models.CharField(blank=True, max_length=200)),
                ('bio', models.CharField(blank=True, max_length=400)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=core.user.models.profile_pic_directory_path)),
                ('is_public', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('modified_at', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('email_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='user.Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='user.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.datetime_safe.datetime.now)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='user.Profile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.Profile')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='userfollowrequest',
            index_together={('source', 'created_at'), ('destination', 'created_at')},
        ),
        migrations.AlterIndexTogether(
            name='userfollow',
            index_together={('source', 'created_at'), ('destination', 'created_at')},
        ),
    ]
