# Generated by Django 2.1 on 2018-08-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180825_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='main_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
