# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-25 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180825_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='main_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
