# Generated by Django 2.1 on 2018-08-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_main_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='main_username',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
